export const Codes = {
    GRX0001:"User registered successfully!",
    GRX0002:"User registration failed!",
    GRX0003:"User already registered in the system!",
    GRX0004:"User logged in successfully!",
    GRX0005:"User login failed!",
    GRX0006:"No user found!",
    GRX0007:"Password mmismatch!",
    GRX0008:"Refresh token not found in headers!",
    GRX0009:"Token is blacklisted!",
    GRX0010:"Tokens refreshed successfully!",
    GRX0011:"Tokens refresh failure!",
    GRX0012:"User logout success!",
    GRX0013:"User logout failed!",
    GRX0014:"Please provide both tokens!",
    GRX0015:"Token verification failed!",
    GRX0016:"Token generation failed!",
    GRX0017:"Access and refresh tokens dont belong to same user!",
    GRX0018:"All admins fetched successfully!",
    GRX0019:"Admins fetch unsuccessful!",
    GRX0020:"Sorry,no admins created yet!",
    GRX0021:"Too many requests from this IP, please try again after 15 minutes.",
    GRX0022:"Assignment uploaded successfully!",
    GRX0023:"Assignment upload failure!",
    GRX0024:'Invalid file type. Only PDF are allowed.',
    GRX0025:'No file uploaded,please upload an assignment also!',
    GRX0026:'No token found!',
    GRX0027:"Access denied: Please use user role to upload assignments and verify token is provided!",
    GRX0028:"Access denied: Please use admin role to accept/reject assignments and verify token is provided!",
    GRX0029:"User information is missing,please check token details!",
    GRX0030:"No username associated with these credentials,please contact admin!",
    GRX0031:"All assignments fetched successfully!",
    GRX0032:"An error occured during fetching assignment/assignments!",
    GRX0033:"No username present in DB with this token!",
    GRX0034:"The admin you are choosing has not been assigned admin role!",
    GRX0035:"An admin is not allowed to upload an assignment!",
    GRX0036:"No data present in DB with this adminName!",
    GRX0037:"Invalid status. Must be 'accepted' or 'rejected.",
    GRX0038:"Assignment updated successfully.",
    GRX0039:"Assignment not found.",
    GRX0040:"Admin not found.",
    GRX0041:"You are not authorized to change/view  as this assignment is not alloted to you.",
    GRX0042:"An error occured during updating assignment!",
    GRX0043:"File not found.",
    GRX0044:"Assignment fetched successfully.",


};
